#!/bin/bash
# 自动获取腾讯云 API 密钥并配置环境变量

echo "=== 自动配置腾讯云 API 密钥 ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 打开浏览器，访问快捷登录链接："
echo "   https://cloud.tencent.com/login/subAccount/100046466581?type=subAccount&username=DevFengyu"
echo ""
echo "2. 输入密码: 0^v{[ANo"
echo ""
echo "3. 登录成功后，访问 API 密钥页面："
echo "   https://console.cloud.tencent.com/cam/capi"
echo ""
echo "4. 查看或创建 API 密钥："
echo "   - 如果已有密钥，点击「显示」查看 SecretKey"
echo "   - 如果没有密钥，点击「新建密钥」创建"
echo ""
echo "5. 复制 SecretId 和 SecretKey，然后运行："
echo ""
echo "   export TENCENTCLOUD_SECRETID='你的SecretId'"
echo "   export TENCENTCLOUD_SECRETKEY='你的SecretKey'"
echo "   ./configure-env.sh"
echo ""
