/** 权限矩阵页面的中文展示名称；英文权限码只作为内部标识保留。 */
const PERMISSION_GROUP_LABELS: Record<string, string> = {
  admin: '系统管理员',
  allocation: '营业额分配',
  appointment: '预约管理',
  card_transaction: '储值卡交易',
  commission: '提成规则',
  coupon: '优惠券管理',
  customer: '顾客管理',
  dashboard: '工作台',
  data_center: '数据中心',
  employee: '员工管理',
  inventory: '门店库存',
  legacy_order: '历史订单核对',
  merchant: '收款商户',
  message: '消息管理',
  operation_log: '操作日志',
  org: '组织架构',
  permission: '权限管理',
  pickup_record: '提货记录',
  point_transaction: '积分交易',
  product: '商品管理',
  sale_item: '销售明细',
  sale_order: '销售订单',
  service: '服务单管理',
  store: '门店管理',
  store_unbind: '顾客解绑申请',
  system: '系统设置',
}

const PERMISSION_ACTION_LABELS: Record<string, string> = {
  'admin:reset_password': '重置员工密码',
  'allocation:list': '查看营业额分配',
  'allocation:save': '保存营业额分配',
  'appointment:checkin': '预约签到',
  'appointment:confirm': '确认预约',
  'appointment:delete': '删除预约',
  'appointment:list': '查看预约',
  'card_transaction:list': '查看储值卡交易',
  'commission:create': '新增提成规则',
  'commission:delete': '删除提成规则',
  'commission:list': '查看提成规则',
  'commission:update': '修改提成规则',
  'coupon:create': '新增优惠券',
  'coupon:list': '查看优惠券',
  'coupon:update': '修改优惠券',
  'customer:create': '新增顾客',
  'customer:delete': '删除顾客',
  'customer:list': '查看顾客',
  'customer:update': '修改顾客',
  'dashboard:view': '查看工作台',
  'data_center:dashboard': '查看数据中心',
  'employee:create': '新增员工',
  'employee:delete': '删除员工',
  'employee:list': '查看员工',
  'employee:update': '修改员工',
  'inventory:create': '新建库存单',
  'inventory:delete': '删除库存单',
  'inventory:export': '导出库存数据',
  'inventory:list': '查看库存单',
  'inventory:stock_list': '查看库存',
  'legacy_order:approve': '审核通过历史订单',
  'legacy_order:list': '查看历史订单',
  'legacy_order:pull': '拉取历史订单',
  'legacy_order:reject': '驳回历史订单',
  'legacy_order:update_amount': '修改历史订单金额',
  'legacy_order:update_phone': '修改历史订单手机号',
  'merchant:create': '新增收款商户',
  'merchant:delete': '删除收款商户',
  'merchant:list': '查看收款商户',
  'merchant:update': '修改收款商户',
  'message:delete': '删除消息',
  'message:list': '查看消息',
  'message:send': '发送消息',
  'operation_log:delete': '删除操作日志',
  'operation_log:list': '查看操作日志',
  'org:create': '新增组织节点',
  'org:delete': '删除组织节点',
  'org:list': '查看组织架构',
  'org:update': '修改组织节点',
  'permission:assign': '分配角色',
  'permission:assign_admin': '分配系统管理员角色',
  'permission:list': '查看权限管理',
  'permission:revoke': '撤销角色',
  'pickup_record:create': '新增提货记录',
  'pickup_record:delete': '删除提货记录',
  'pickup_record:list': '查看提货记录',
  'point_transaction:list': '查看积分交易',
  'product:create': '新增商品',
  'product:list': '查看商品',
  'product:update': '修改商品',
  'sale_item:list': '查看销售明细',
  'sale_order:create': '新建销售订单',
  'sale_order:delete': '删除销售订单',
  'sale_order:deposit_approve': '审核定金订单',
  'sale_order:list': '查看销售订单',
  'sale_order:record_payment': '登记订单收款',
  'sale_order:refund_approve': '审核订单退款',
  'sale_order:refund_create': '发起订单退款',
  'sale_order:update': '修改销售订单',
  'service:create': '新建服务单',
  'service:delete': '删除服务单',
  'service:list': '查看服务单',
  'service:update': '修改服务单',
  'store:create': '新增门店',
  'store:lakala_config': '配置拉卡拉收款',
  'store:list': '查看门店',
  'store:update': '修改门店',
  'store_unbind:approve': '同意顾客解绑',
  'store_unbind:delete': '删除解绑申请',
  'store_unbind:list': '查看解绑申请',
  'store_unbind:reject': '驳回顾客解绑',
  'system:config': '管理系统设置',
}

export function getPermissionGroupLabel(group: string): string {
  return PERMISSION_GROUP_LABELS[group] ?? '未分类权限'
}

export function getPermissionActionLabel(action: string): string {
  return PERMISSION_ACTION_LABELS[action] ?? '未命名权限'
}

export function hasPermissionActionLabel(action: string): boolean {
  return action in PERMISSION_ACTION_LABELS
}
