const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {calendarMonth,calendarPeriod,calendarRule,calendarPlan,calendarPreview,ensureCalendar}=require('../utils/daily-calendar-auto');
const natural={start:{monthOffset:0,day:1},end:{monthOffset:0,day:31},weeks:[[1,7],[8,14],[15,21],[22,31]].map(([a,b],i)=>({id:'w'+i,name:'第'+(i+1)+'周',start:{monthOffset:0,day:a},end:{monthOffset:0,day:b}}))};
const cross={start:{monthOffset:-1,day:26},end:{monthOffset:0,day:25},weeks:[[-1,26,0,2],[0,3,0,9],[0,10,0,16],[0,17,0,25]].map(([a,b,c,d],i)=>({id:'w'+i,name:'第'+(i+1)+'周',start:{monthOffset:a,day:b},end:{monthOffset:c,day:d}}))};
function data(pattern=natural){return {regions:[{id:'a',name:'市场A'},{id:'b',name:'市场B'}],templates:[{id:'t',region_id:null,pattern}],overrides:[],history:[],modes:[],disabled:[],periods:[],stores:[{store_id:'sa',region_id:'a'},{store_id:'sb',region_id:'b'}]};}
function saved(month,pattern=natural,region=null){const p=calendarPeriod(month,pattern);return {id:'old'+month+region,name:p.name,month_key:month,region_id:region,start_date:p.start,end_date:p.end,weeks:p.weeks,version:7};}
test('自然月短月、闰年、跨年、跨月及可变周',()=>{assert.equal(calendarPeriod('2028-02',natural).end,'2028-02-29');assert.equal(calendarPeriod('2027-02',natural).end,'2027-02-28');assert.equal(calendarMonth('2027-12',1),'2028-01');assert.equal(calendarPeriod('2028-02',cross).start,'2028-01-26');const p={...natural,weeks:[{id:'one',name:'整月',start:natural.start,end:natural.end}]};assert.equal(calendarPeriod('2028-02',p).weeks.length,1);assert.throws(()=>calendarPeriod('2028-02',{...natural,weeks:natural.weeks.slice(0,1)}),/覆盖完整/);});
test('当前缺少安排按已保存规则创建，后续两月一起安排',()=>{const rows=calendarPlan(data(),'2026-10-08');assert.equal(rows.length,6);assert.deepEqual(rows.slice(0,3).map(r=>r.monthKey),['2026-10','2026-11','2026-12']);assert.equal(rows[0].period.start,'2026-10-01');});
test('跨月当前归属月在月末自动前移，不靠客户端月份',()=>{const rows=calendarPlan(data(cross),'2026-10-28');assert.equal(rows[0].monthKey,'2026-11');assert.equal(rows[0].period.start,'2026-10-26');});
test('历史、当前、未来已有安排全部保留，旧全局编号和周保持不变',()=>{const d=data();d.periods=['2026-09','2026-10','2026-11','2026-12'].map(k=>saved(k));const before=JSON.stringify(d.periods);const rows=calendarPlan(d,'2026-10-08');assert.ok(rows.every(r=>r.existing));assert.equal(JSON.stringify(d.periods),before);assert.equal(calendarPreview(d,d.regions[0],'2026-11').status,'已配置，保留原安排');});
test('特殊市场优先，生效日期前仍用旧版本，月份例外不改其他月份',()=>{const d=data();d.history=[{validFrom:'0001-01-01',modes:[{id:'base',isDefault:true,regionIds:[],pattern:natural}]},{validFrom:'2026-10-08',modes:[{id:'base',isDefault:true,regionIds:[],effectiveFrom:'2026-10-08',pattern:natural},{id:'special',isDefault:false,regionIds:['b'],effectiveFrom:'2026-10-08',pattern:cross}]}];assert.equal(calendarRule(d,'b','2026-10').modeId,'base');assert.equal(calendarRule(d,'b','2026-11').modeId,'special');const p={...natural,weeks:[{id:'one',name:'整月',start:natural.start,end:natural.end}]};d.history[0].modes[0].monthly={'2026-09':p};assert.equal(calendarRule(d,'a','2026-09').pattern.weeks.length,1);assert.equal(calendarRule(d,'a','2026-10').pattern.weeks.length,4);});
test('相邻旧月份日期断档或重叠拒绝，不能自动改旧日期',()=>{const d=data();d.periods=[saved('2026-10',cross)];assert.throws(()=>calendarPlan(d,'2026-10-08'),/不连续/);const d2=data(cross);d2.periods=[saved('2026-10',natural)];assert.throws(()=>calendarPlan(d2,'2026-10-08'),/重叠/);});
test('无生效规则不能猜测当前月份，过去日期预览不写库',()=>{const d=data();d.templates=[];assert.throws(()=>calendarPlan(d,'2026-10-08'),/没有可用/);assert.equal(calendarPreview(data(),{id:'a',name:'A'},'2020-01').monthKey,'2020-01');});
test('自动写入只在锁内，限定授权市场，重复调用幂等且拒绝客户端任意范围',async()=>{const d=data();let inserts=0,locks=0;const query=async(sql,args=[])=>{if(sql.includes('pg_advisory_xact_lock')){locks++;return []}if(sql.includes("FROM org_nodes WHERE type="))return d.regions;if(sql.includes('FROM daily_operating_period_templates'))return d.templates;if(sql.includes('FROM daily_operating_period_overrides'))return [];if(sql.includes('FROM daily_operating_periods'))return d.periods;if(sql.includes('FROM system_configs'))return [];if(sql.startsWith('WITH RECURSIVE'))return d.stores;if(sql.startsWith('INSERT INTO daily_operating_periods')){inserts++;d.periods.push({id:args[0],name:args[1],start_date:args[2],end_date:args[3],weeks:JSON.parse(args[4]),region_id:args[5],month_key:args[6]});return []}if(sql.startsWith('INSERT INTO operation_logs'))return [];if(sql.startsWith('INSERT INTO daily_operating_period_stores')){assert.deepEqual(args[1],['sa']);return []}throw Error(sql)};assert.equal((await ensureCalendar(query,['sa'],'2026-10-08')).created,3);assert.equal((await ensureCalendar(query,['sa'],'2026-10-08')).created,0);assert.equal(inserts,3);assert.equal(locks,2);assert.ok(d.periods.every(p=>p.region_id==='a'));await assert.rejects(()=>ensureCalendar(query,['sa'],'2026-10-08','2020-01'),/未来12个月/);await assert.rejects(()=>ensureCalendar(query,['sa'],'2026-10-08','2028-01'),/未来12个月/);});
test('跨端独立实现字节一致（TS转JS），防止日期规则漂移',()=>{const ts=require('../../../../fengyu-admin/node_modules/typescript');const source=fs.readFileSync(path.resolve(__dirname,'../../../../fengyu-admin/src/lib/daily-calendar-auto.ts'),'utf8');const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText;assert.equal(fs.readFileSync(path.resolve(__dirname,'../utils/daily-calendar-auto.js'),'utf8'),compiled);});
test('区域特殊月份优先于同月旧全局安排，后续补齐不被旧全局日期误阻挡',()=>{
 const d=data();d.regions=d.regions.filter(r=>r.id==='a');
 const global=saved('2028-03');global.end_date='2028-04-05';
 d.periods=[global,saved('2028-03',natural,'a')];
 const before=JSON.stringify(d.periods), rows=calendarPlan(d,'2028-03-08');
 assert.equal(rows[0].period.id,'old2028-03a');assert.equal(rows[1].period.start,'2028-04-01');
 assert.equal(JSON.stringify(d.periods),before);
});
