#!/usr/bin/env node
// 生成 src/generated/version.ts —— 在 dev / build 前自动跑（package.json 的 predev/prebuild 钩子）。
//
// 版本号来源优先级：
//   1. 环境变量 APP_VERSION / APP_COMMIT（Docker 构建场景，由 --build-arg 注入）
//   2. monorepo 根目录的 git：
//        git describe --tags --abbrev=0 --match 'v*'   → APP_VERSION
//        git rev-parse --short HEAD                    → APP_COMMIT
//   3. 都失败则 version="dev"、commit=""
//
// 之所以过滤 'v*'：仓库里还有 `p2-14-phase-d-done` 这类里程碑 tag，不过滤会错取。

import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const adminRoot = resolve(__dirname, "..");
const repoRoot = resolve(adminRoot, "..");
const outPath = resolve(adminRoot, "src/generated/version.ts");

function tryGit(cmd) {
  try {
    return execSync(cmd, {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

const version =
  process.env.APP_VERSION ||
  tryGit("git describe --tags --abbrev=0 --match 'v*'") ||
  "dev";

const commit =
  process.env.APP_COMMIT || tryGit("git rev-parse --short HEAD") || "";

const buildTime = new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.
// Regenerated on every \`bun run dev\` / \`bun run build\` via package.json hooks.

export const APP_VERSION = ${JSON.stringify(version)};
export const APP_COMMIT = ${JSON.stringify(commit)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, "utf8");

console.log(
  `[gen-version] ${version}${commit ? ` · ${commit}` : ""} → src/generated/version.ts`,
);
