#!/usr/bin/env node











import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const adminRoot = resolve(__dirname, "..");
const repoRoot = resolve(adminRoot, "..");
const outPath = resolve(adminRoot, "src/generated/version.ts");

function tryGit(cmd) {
  try {
    return execSync(cmd, {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

const version =
  process.env.APP_VERSION ||
  tryGit("git describe --tags --abbrev=0 --match 'v*'") ||
  "dev";

const commit =
  process.env.APP_COMMIT || tryGit("git rev-parse --short HEAD") || "";

const buildTime = new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.
// Regenerated on every \`bun run dev\` / \`bun run build\` via package.json hooks.

export const APP_VERSION = ${JSON.stringify(version)};
export const APP_COMMIT = ${JSON.stringify(commit)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, "utf8");

console.log(
  `[gen-version] ${version}${commit ? ` · ${commit}` : ""} → src/generated/version.ts`,
);
